# -*- coding: utf-8 -*-
"""Lab 11-07

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kh7jaXXMiQadmf7TeZGCbJyKIe2Gsq00
"""

i = 1
while True:
    if i%3 == 0:
        break
    print(i)
    i += 1

class_code_str = '3501'

class_code_int = 3501
print('Class Code: ' + class_code_str)
print(f'Class Code: {class_code_int}')
print(f'Class Code: {class_code_str}')
print('Class Code: ' + str(class_code_int))

print('Class Code: ' + class_code_int)

A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(A[1][2])

import seaborn as sns
iris = sns.load_dataset('iris')

import seaborn as sns
iris = sns.load_dataset('iris')
virginica_sepal_width = iris[iris['species'] == 'virginica']['sepal_width'].min()
print(f"Minimum sepal_width for 'virginica' variety: {virginica_sepal_width}")



import seaborn as sns
titanic = sns.load_dataset('titanic')

# Filter for 2nd class passengers who survived
survived_2nd_class = titanic[(titanic['pclass'] == 2) & (titanic['survived'] == 1)]

# Count the number of observations
num_survived_2nd_class = len(survived_2nd_class)

print(f"Number of passengers in 2nd class who survived: {num_survived_2nd_class}")

average_sepal_length_by_species = iris.groupby('species')['sepal_length'].mean()
print("Average sepal_length by species:")
print(average_sepal_length_by_species)

largest_sepal_length_species = average_sepal_length_by_species.idxmax()
max_sepal_length_value = average_sepal_length_by_species.max()

print(f"\nSpecies with the largest average sepal_length: {largest_sepal_length_species} ({max_sepal_length_value:.2f})")

largest_sepal_length = iris['sepal_length'].max()
print(f"The largest sepal_length is: {largest_sepal_length}")

std_sepal_length = iris['sepal_length'].std()
print(f"Standard deviation of sepal_length: {std_sepal_length:.2f}")

average_sepal_width_by_species = iris.groupby('species')['sepal_width'].mean()
print("Average sepal_width by species:")
print(average_sepal_width_by_species)

largest_sepal_width_species = average_sepal_width_by_species.idxmax()
max_sepal_width_value = average_sepal_width_by_species.max()

print(f"\nSpecies with the largest average sepal_width: {largest_sepal_width_species} ({max_sepal_width_value:.2f})")

missing_values = titanic.isnull().sum()
variables_with_missing_values = missing_values[missing_values > 0]

if not variables_with_missing_values.empty:
    print("Variables with missing values in the titanic dataset:")
    print(variables_with_missing_values)
else:
    print("There are no missing values in the titanic dataset.")

female_passengers = titanic[titanic['sex'] == 'female']
num_female_survived = female_passengers['survived'].sum()
total_female_passengers = len(female_passengers)

percentage_female_survived = (num_female_survived / total_female_passengers) * 100
rounded_percentage = round(percentage_female_survived)

print(f"Percentage of female passengers who survived: {rounded_percentage}%")

first_class_not_survived = titanic[(titanic['pclass'] == 1) & (titanic['survived'] == 0)]

min_age_1st_class_not_survived = first_class_not_survived['age'].min()
max_age_1st_class_not_survived = first_class_not_survived['age'].max()

print(f"Age range for 1st class passengers who did not survive: {min_age_1st_class_not_survived} to {max_age_1st_class_not_survived}")

import pandas as pd

# Calculate the correlation matrix for numerical columns
correlation_matrix = iris.select_dtypes(include=['number']).corr()

# Exclude self-correlations and duplicate pairs by taking the upper triangle
corr_unstacked = correlation_matrix.unstack()
sorted_corr = corr_unstacked.sort_values(kind="quicksort", ascending=False)

# Filter out self-correlations (correlation of a variable with itself is always 1)
# and take only the upper triangle to avoid duplicate pairs (e.g., A-B and B-A)
positive_correlations = sorted_corr[sorted_corr < 1]

# Get the highest positive correlation pair
highest_positive_corr_pair = positive_correlations.drop_duplicates().iloc[[0]]

print("Variable pair with the highest Pearson correlation:")
print(highest_positive_corr_pair)

print(f"Number of observations in df_petal_length_greater_than_mean: {df_petal_length_greater_than_mean.shape[0]}")

mean_petal_length = iris['petal_length'].mean()
df_petal_length_greater_than_mean = iris[iris['petal_length'] > mean_petal_length]

print(f"Mean petal_length of the whole iris dataset: {mean_petal_length:.2f}")
display(df_petal_length_greater_than_mean.head())

class_code_str = '3501'

class_code_int = 3501

import seaborn as sns
iris = sns.load_dataset('iris')

mean_sepal_length = iris['sepal_length'].mean()
print(f"Mean sepal_length: {mean_sepal_length:.2f}")

import seaborn as sns
titanic = sns.load_dataset('titanic')

survival_rate_s = titanic[titanic['embark_town'] == 'Southampton']['survived'].mean()
survival_rate_c = titanic[titanic['embark_town'] == 'Cherbourg']['survived'].mean()

print(f"Survival Rate for passengers embarked at Southampton (S): {survival_rate_s:.2%}")
print(f"Survival Rate for passengers embarked at Cherbourg (C): {survival_rate_c:.2%}")

survival_rate_by_class = titanic.groupby('pclass')['survived'].mean()
print("Survival Rate by Passenger Class:")
print(survival_rate_by_class.apply(lambda x: f'{x:.2%}'))

correlation_survival_fare = titanic[['survived', 'fare']].corr().loc['survived', 'fare']
print(f"Correlation between Survival and Fare: {correlation_survival_fare:.2f}")

correlation_survival_pclass = titanic[['survived', 'pclass']].corr().loc['survived', 'pclass']
print(f"Correlation between Survival and Passenger Class: {correlation_survival_pclass:.2f}")

virginica_sepal_width = iris[iris['species'] == 'virginica']['sepal_width'].min()
print(f"Minimum sepal_width for 'virginica' variety: {virginica_sepal_width}")

num_virginica = len(iris[iris['species'] == 'virginica'])
print(f"Number of 'virginica' entries: {num_virginica}")

num_species = iris['species'].nunique()
print(f"Number of unique species: {num_species}")

num_versicolor = len(iris[iris['species'] == 'versicolor'])
print(f"Number of 'versicolor' entries: {num_versicolor}")